### PR TITLE
Allow custom data on table node

### PR DESCRIPTION
**Pull request by YurkaninRyan**
This PR stops the plugin from overwriting whatever data a user wants to set on their tables

What do you think about this?  Would there be a better way?

### CODE REVIEW

**Comment by YurkaninRyan** [comment]
I mentioned this problem in #36.  It is possible to setNodeByKey on a table currently, but some operations cause it to lose data.  Mainly inserting and removing columns.

**Comment by Soreine** [comment]
Ok I have tried using `data.merge` instead of `Object.assign`, but it fails on some tests.
I noticed that doing `data.merge(...).toJS()` would make tests pass. We should look into what Slate is doing on `setNodeByKey`, to better understand.

It would be worth adding a test for this feature too (having custom data on rows/tables, doing some table operation, and see if they are preserved).

**Comment by YurkaninRyan** [comment]
Got it @Soreine I'll take a look through it 👍

**Comment by YurkaninRyan** [comment]
Hey @Soreine I have a theory that it has to do with the fact that `.merge` coerces the array return from `createAlign` into an immutable `List`.  I'm looking for where this might cause loops and or bugs right now

**Comment by Soreine** [comment]
Closed in favor of #43

**Pull request closed without merging**
