### PR TITLE
Compat slate@0.30.6

### PR DESCRIPTION
**Pull request by Soreine**
- [x] Upgrade to slate 0.30.x
- [x] Add prettier
- [x] Add flow
- [x] Cleanup lib structure 
- [x] Allow to `import EditTableCore from 'slate-edit-table/lib/core`, to use in a non react environment, without rendering etc. Doing so gives access to schema, changes, utils, but not the behavior part of the plugin.
- [ ] Convert all rules to new schema format. Not all rules can be converted (e.g. rules counting columns). Most can. But I was not able to convert them all yet (bugs).

### CODE REVIEW

**Comment by Soreine** [comment]
At this point, this PR is mergeable. 

Not all rules have been converted to the new schema format, because of a weird bug I have when trying to convert the rule `tablesContainOnlyRows` (slate seems to be calling normalization on a node that was removed).

**Comment by Soreine** [comment]
Some rules cannot be converted yet to the new schema, because they currently lead to bugs:
https://github.com/ianstormtaylor/slate/issues/1363

**Comment by Soreine** [comment]
We will convert rules to schema in a later PR

**Comment by CameronAckermanSEL** [comment]
Any update on this?

**Comment by Soreine** [comment]
I'll publish it as is. I was waiting on https://github.com/ianstormtaylor/slate/issues/1363

**Pull request merged**
